@startuml
skinparam classAttributeIconSize 0
hide empty members

class HerosFactory
{
	+newHero(name)
}

abstract Heroes
{
#Weapons
#HitPoint
#attack
#defence
}

abstract Weapons
{
	#Damage
	#HitPoint
}
class Weapons1
{
+Weapons1()
}
class Weapons2
{
+Weapons2()
}

class Coordinates
{
#x
#y
}

class Hero1
{
+Hero1(long p_id, string p_name, Coordinates p_coordinate)
+void Attack()
}

class Hero2
{
+Hero2(long p_id, string p_name, Coordinates p_coordinate)
+void Attack()
}

Coordinates -* Heroes
Heroes <|-- Hero1
Heroes <|-- Hero2
Weapons <|-- Weapons1
Weapons <|-- Weapons2

Hero1 -[hidden]- HerosFactory

@enduml
